# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "NoriS"
description: > # this means to ignore newlines until "email:"
   Make Your Work More Fun

email: joshua@noriter.dev
#web logo
logo: "/assets/images/NoriS_CI.jpg"
float_logo: true # true, false (default)

# web cover
cover: "/assets/images/247122.jpg"

name: 'NoriS'
author: 'Joshua'
author_image: "/assets/images/joshua.jpg"

paginate:	5

url: "http://noriter.dev" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  # - icon:	twitter
  #   url:	https://twitter.com/dirkfabisch
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/dirkfabisch
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
